ollama:
  llm_model: "llama3.2:3b"
  embedding_model: "nomic-embed-text:latest"


qdrant:
  host: "localhost"
  port: 6333
  collection_name: "hr_policy_collection"
  vector_size: 768

document:
  pdf_path: "hr_policy_detailed_5_pages.pdf"